---

- name: "configuration play." 
  hosts: web
  remote_user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_host_key_checking: false
    ansible_stdout_callback: yaml
    ansible_host: 54.82.113.44

  roles:
    - configure-server
    - configure-prometheus-node-exporter

  # # Get the environment variables from CircleCI and add to the EC2 instance
  # environment:
  #   - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"  
  #   # Add more env vars here