---
- name: "create backend dir for unarchiving the artifact"
  file:
    path:  /home/ubuntu/backend
    state: directory

- name: "unarchive artifact files"
  unarchive:
    src: artifact.tar.gz
    dest:  /home/ubuntu/backend

- name: "Install the dependancies"
  shell: |
    cd  /home/ubuntu/backend
    npm i

- name: "Execute the app"
  shell: |
    cd  /home/ubuntu/backend/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: "Configure pm2 to start as  a service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
 